language: c

compiler:
  - gcc-6

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - autopoint
    - bison
    - gcc-6
    - help2man
    - texinfo

script: ./autogen.sh && ./configure && make && make check
