language: c

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - automake
    - bison
    - gcc-6
    - gettext
    - help2man
    - texinfo
